Sync with upstream BlastEm (hg tip 732f5689d438)
This repo has been sitting on the July 2022 state of upstream BlastEm. The
sync brings in four years of upstream work, most importantly for this repo
the DSL generated CPU cores: upstream's Makefile now switches to NEW_CORE
automatically on any architecture that has no native code generator, and
genesis.h picks up the generated m68k context in that configuration, which
is what makes non-x86 builds possible at all.

Only .gitlab-ci.yml and Makefile.libretro are kept from this repo, every
other file is upstream's.

diff --git a/build_release b/build_release
--- a/build_release
+++ b/build_release
@@ -5,20 +5,30 @@ set -e
 if [ -z "$OS" ]; then
 	OS=`uname -s`
 fi
-
+SDL="sdl2"
 if [ $OS = "Linux" ]; then
-	cd sdl
-	./configure
-	make all
-	cd ..
 	rm -rf lib
 	mkdir lib
-	cp sdl/build/.libs/libSDL2-*.so.*.*.* lib
-	sdl=`ls lib`
-	link=`echo $sdl | sed -E 's/(so\.[0-9]*).*/\1/'`
-	cd lib
-	ln -s "$sdl" "$link"
-	ln -s "$sdl" libSDL2.so
+	cd sdl
+	if [ -f ./configure ]; then
+		./configure
+		make all
+		cd ..
+		cp sdl/build/.libs/libSDL2-*.so.*.*.* lib
+		sdl=`ls lib`
+		link=`echo $sdl | sed -E 's/(so\.[0-9]*).*/\1/'`
+		cd lib
+		ln -s "$sdl" "$link"
+		ln -s "$sdl" libSDL2.so
+	elif [ -f ./CMakeLists.txt ]; then
+		cmake -S . -B build
+		cmake --build build
+		cp build/libSDL3.so* ../lib
+		SDL="sdl3"
+	else
+		echo "Failed to find SDL build file!";
+		exit 1
+	fi
 	cd ..
 	cd glew
 	make all
@@ -26,19 +36,19 @@ if [ $OS = "Linux" ]; then
 fi
 echo "Path is: $PATH"
 if [ $OS = "Win64" ]; then
-	make PORTABLE=1 OS=Windows CPU=x86_64 clean all
+	make PORTABLE=1 OS=Windows CPU=x86_64 SDL=$SDL clean all
 	SDLDLLPATH=sdl/x86_64-w64-mingw32/bin
 else
-	make PORTABLE=1 clean all
+	make PORTABLE=1 SDL=$SDL clean all
 	SDLDLLPATH=sdl/i686-w64-mingw32/bin
 fi
 make menu.bin tmss.md
 if [ $OS = "Windows" -o $OS = "Win64" ]; then
-	binaries="dis.exe zdis.exe vgmplay.exe blastem.exe $SDLDLLPATH/SDL2.dll"
-	verstr=`sed -E -n 's/^[^B]+BLASTEM_VERSION "([^"]+)"/blastem \1/p' blastem.c`
+	binaries="blastem.exe $SDLDLLPATH/SDL2.dll"
+	verstr=`sed -E -n 's/^[^B]+BLASTEM_VERSION "([^"]+)"/blastem \1/p' version.inc`
 	txt=".txt"
 else
-	binaries="dis zdis vgmplay blastem termhelper"
+	binaries="dis zdis blastem termhelper"
 	if [ $OS = "Darwin" ]; then
 		binaries="$binaries Frameworks"
 	else
@@ -68,8 +78,10 @@ for file in README COPYING CHANGELOG; do
 done
 if [ $OS = "Darwin" ]; then
 	cp SDL-LICENSE "$dir"
-else
+elif [ $OS = "Windows" -o $OS = "Win64" ]; then
 	cp sdl/COPYING.txt "$dir"/SDL-LICENSE$txt
+else
+	cp sdl/LICENSE.txt "$dir"/SDL-LICENSE$txt
 fi
 cp glew/LICENSE.txt "$dir"/GLEW-LICENSE$txt
 
